version: 0.2
phases:
  build:
    commands:
      - echo "Building the Vue frontend"
      - cd "frontend"
      - npm run build

      - cd ..

      - echo "Building the lambda backend.."

      # Build lambda layer artifacts
      - echo "Building the lambda layers.."
      - cd backend

      - cd layers
      - mkdir python

      - echo "Building the domain layer.."
      - cp domain python/ -r
      - zip -r ../domain.zip ./python/
      - rm -rf python/*

      - echo "Building the dynamo_utils layer.."
      - cp dynamo_utils python/ -r
      - zip -r ../dynamo_utils.zip ./python/
      - rm -rf python/*

      - echo "Building the simulator layer.."
      - cp simulator python/ -r
      - zip -r ../simulator.zip ./python/
      - rm -rf python/*

      - echo "Building the writer layer.."
      - cp writer python/ -r
      - zip -r ../writer.zip ./python/
      - rm -rf python/*

      - cd ..
    
      # Build lambda function artifacts
      - echo "Building the lambda functions.."
      - cd handlers

      - echo "Building the create user lambda"
      - cp create-user-lambda.py lambda_function.py
      - zip ../create-user-deployment.zip lambda_function.py

      - echo "Building the delete scenario lambda"
      - cp delete-scenario-lambda.py lambda_function.py
      - zip ../delete-scenario-deployment.zip lambda_function.py

      - echo "Building the get scenario lambda"
      - cp get-scenario-lambda.py lambda_function.py
      - zip ../get-scenario-deployment.zip lambda_function.py

      - echo "Building the get scenarios lambda"
      - cp get-scenarios-lambda.py lambda_function.py
      - zip ../get-scenarios-deployment.zip lambda_function.py

      - echo "Building the get user lambda"
      - cp get-user-lambda.py lambda_function.py
      - zip ../get-user-deployment.zip lambda_function.py

      - echo "Building the patch scenario lambda"
      - cp patch-scenario-lambda.py lambda_function.py
      - zip ../patch-scenario-deployment.zip lambda_function.py

      - echo "Building the patch user lambda"
      - cp patch-user-lambda.py lambda_function.py
      - zip ../patch-user-deployment.zip lambda_function.py

      - echo "Building the post scenario lambda"
      - cp post-scenario-lambda.py lambda_function.py
      - zip ../post-scenario-deployment.zip lambda_function.py

      - cd ..
  
  post_build:
    commands: 
      - echo "Publishing the lambda layers"

      - echo "Publishing the domain layer.."
      - aws lambda publish-layer-version --layer-name RetireRightDomain --zip-file fileb://domain.zip --compatible-architectures x86_64 --compatible-runtimes python3.9

      - echo "Publishing the dynamo_utils layer.."
      - aws lambda publish-layer-version --layer-name RetireRightDynamoUtils --zip-file fileb://dynamo_utils.zip --compatible-architectures x86_64 --compatible-runtimes python3.9

      - echo "Publishing the writer layer.."
      - aws lambda publish-layer-version --layer-name RetireRightWriter --zip-file fileb://writer.zip --compatible-architectures x86_64 --compatible-runtimes python3.9

      - echo "Publishing the simulator layer.."
      - aws lambda publish-layer-version --layer-name RetireRightSimulator --zip-file fileb://simulator.zip --compatible-architectures x86_64 --compatible-runtimes python3.9

      - echo "Retrieving latest versions of lambda layers"
      - >
        latestdomain=`aws lambda list-layer-versions --layer-name RetireRightDomain --max-items 1 | grep LayerVersionArn | sed 's/"LayerVersionArn": "//' | cut -d'"' -f1 | tr -s " "`
      - > 
        latestDynamoUtils=`aws lambda list-layer-versions --layer-name RetireRightDynamoUtils --max-items 1 | grep LayerVersionArn | sed 's/"LayerVersionArn": "//' | cut -d'"' -f1 | tr -s " "`
      - >
        latestWriter=`aws lambda list-layer-versions --layer-name RetireRightWriter --max-items 1 | grep LayerVersionArn | sed 's/"LayerVersionArn": "//' | cut -d'"' -f1 | tr -s " "`
      - >
        latestSimulator=`aws lambda list-layer-versions --layer-name RetireRightSimulator --max-items 1 | grep LayerVersionArn | sed 's/"LayerVersionArn": "//' | cut -d'"' -f1 | tr -s " "`
      
      - echo "Retrieved the following layer ARNs and versions:"
      - echo $latestdomain
      - echo $latestDynamoUtils
      - echo $latestWriter
      - echo $latestSimulator

      - echo "Updating lambda functions.."

      - echo "Updating create-user-lambda.."
      - echo "Updating create-user-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name create-user-lambda --layers ${latestdomain} ${latestDynamoUtils}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name create-user-lambda --zip-file fileb://create-user-deployment.zip

      - echo "Updating delete-scenario-lambda.."
      - echo "Updating delete-scenario-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name delete-scenario-lambda --layers ${latestdomain} ${latestDynamoUtils} ${latestWriter}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name delete-scenario-lambda --zip-file fileb://delete-scenario-deployment.zip 

      - echo "Updating get-scenario-lambda.."
      - echo "Updating get-scenario-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name get-scenario-lambda --layers ${latestdomain} ${latestDynamoUtils} ${latestWriter}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name get-scenario-lambda --zip-file fileb://get-scenario-deployment.zip

      - echo "Updating get-scenarios-lambda.."
      - echo "Updating get-scenarios-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name get-scenarios-lambda --layers ${latestdomain} ${latestDynamoUtils} ${latestWriter}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name get-scenarios-lambda --zip-file fileb://get-scenarios-deployment.zip

      - echo "Updating get-user-lambda.."
      - echo "Updating get-user-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name get-user-lambda --layers ${latestdomain} ${latestDynamoUtils} ${latestWriter}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name get-user-lambda --zip-file fileb://get-user-deployment.zip 

      - echo "Updating patch-scenario-lambda.."
      - echo "Updating patch-scenario-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name patch-scenario-lambda --layers ${latestdomain} ${latestDynamoUtils} ${latestWriter} ${latestSimulator}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name patch-scenario-lambda --zip-file fileb://patch-scenario-deployment.zip

      - echo "Updating patch-user-lambda.."
      - echo "Updating patch-user-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name patch-user-lambda --layers ${latestdomain} ${latestDynamoUtils} ${latestWriter} ${latestSimulator}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name patch-user-lambda --zip-file fileb://patch-user-deployment.zip 

      - echo "Updating post-scenario-lambda.."
      - echo "Updating post-scenario-lambda to use latest layers it requires.."
      - echo "Updating to use the latest layers"
      - aws lambda update-function-configuration --function-name post-scenario-lambda --layers ${latestdomain} ${latestDynamoUtils} ${latestWriter} ${latestSimulator}
      - echo "Sleeping for 30 seconds"
      - sleep 30
      - echo "Updating to use the latest code"
      - aws lambda update-function-code --function-name post-scenario-lambda --zip-file fileb://post-scenario-deployment.zip


artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    lambda_functions:
      base-directory:
        backend
      files:
        - create-user-deployment.zip
        - delete-scenario-deployment.zip
        - get-scenario-deployment.zip
        - get-scenarios-deployment.zip
        - get-user-deployment.zip
        - patch-scenario-deployment.zip
        - patch-user-deployment.zip
        - post-scenario-deployment.zip
      name: lambda_functions
    lambda_layers:
      base-directory:
        backend
      files:
        - domain.zip
        - dynamo_utils.zip
        - simulator.zip
        - writer.zip
    frontend:
      base-directory:
        frontend
      files:
        - dist/*

